version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/_static
      - media_volume:/app/_media
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn django_doit.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - static_volume:/app_static
      - media_volume:/app_media
      - ./:/app
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # environment:
    #   - POSTGRES_USER=chae1234_db_user
    #   - POSTGRES_PASSWORD=chae1234_db_password
    #   - POSTGRES_DB=chae1234_dev
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data:
  static_volume:
  media_volume: